### ISSUE TITLE
WebGL support

### ISSUE THREAD

**Issue by zaixiaoqu** [gilzoide/unity-lottie-player#4]
Cannot be used normally in webgl environment.
<img width="710" alt="image" src="https://github.com/gilzoide/unity-lottie-player/assets/27716973/ab7355ca-7be8-4d69-a6d3-fa37e1eb37b4">

**Comment by gilzoide** [comment]
Hey @zaixiaoqu, thanks for the report!
I've been able to reproduce here the error "Uncaught ...", although I don't get this "abnormal situation has occurred" one.

Maybe WebGL builds don't play nice with the C# Job System, we'll probably need some special handling for WebGL specifically. Shouldn't be too hard, though, running the jobs synchronously instead of async.

**Comment by gilzoide** [comment]
Ok, I think I found it. Disabling `LOTTIE_THREAD_SUPPORT` from the WebGL native build seems to fix the problem =]
I'll create a PR with the fix soon.

**Comment by gilzoide** [comment]
Ok, this problem should be fixed in the `main` branch, now tagged with `1.0.0-preview1`.
Feel free to reopen this issue if the problem persists.
Cheers \o/

**Comment by zaixiaoqu** [comment]
Thank you so much, I have already tested it, Perfect.
